/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Modern Retro (Stitch Option 1)
        primary: '#a43716',
        'primary-container': '#c54f2c',
        'primary-fixed': '#ffdbd1',
        'primary-fixed-dim': '#ffb5a0',
        secondary: '#8b4e3e',
        'secondary-container': '#fdad99',
        'secondary-fixed': '#ffdbd2',
        'secondary-fixed-dim': '#ffb4a1',
        tertiary: '#973b67',
        'tertiary-fixed': '#ffd9e5',
        'tertiary-container': '#b55380',
        'on-tertiary-fixed-variant': '#7c2551',
        'on-secondary-container': '#793f2f',
        'on-secondary-fixed': '#380d03',
        'on-primary-container': '#fffbff',
        'on-tertiary-container': '#fffbff',
        accent: '#a43716',
        accentDark: '#862201',
        text: '#1d1c15',
        bg: '#fff9ee',
        background: '#fff9ee',
        surface: '#fff9ee',
        'surface-bright': '#fff9ee',
        'surface-container': '#f3ede2',
        'surface-container-low': '#f9f3e8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ede8dd',
        'on-surface': '#1d1c15',
        'on-surface-variant': '#58423c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-background': '#1d1c15',
        'outline-variant': '#dfc0b7',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        shadowRetro: '#a43716',
        goldenOrange: '#fdad99',
      },
      fontFamily: {
        display: ['var(--font-bricolage)', 'Bricolage Grotesque', 'sans-serif'],
        heading: ['var(--font-bricolage)', 'Bricolage Grotesque', 'sans-serif'],
        body: ['var(--font-dm-sans)', 'DM Sans', 'sans-serif'],
        label: ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        script: ['var(--font-dancing)', 'Dancing Script', 'cursive'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
        'h1-mobile': ['36px', { lineHeight: '1.1', fontWeight: '700' }],
        h2: ['48px', { lineHeight: '1.15', fontWeight: '700' }],
        h3: ['32px', { lineHeight: '1.25', fontWeight: '600' }],
        body: ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-mobile': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        small: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        button: ['14px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px',
        s: '8px',
        m: '16px',
        l: '24px',
        xl: '48px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        container: '100%',
        'container-sm': '640px',
        'container-md': '768px',
        'container-lg': '1024px',
        'container-xl': '1200px',
        'container-2xl': '1280px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        marquee: 'marquee 20s linear infinite',
        float: 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #fff9ee 0%, #ffdbd1 42%, #ffd9e5 100%)',
      },
    },
  },
  plugins: [],
};
